import React from 'react';
import { ToastContainer } from 'react-toastify';
import './global.css';
import 'react-toastify/dist/ReactToastify.css';
import Provider from './Provider';
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};
export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang="en">
        <body>
          {children}
          <ToastContainer />
          <ReactQueryDevtools />
        </body>
      </html>
    </Provider>
  );
}
